export { createDb, type DB } from "./db";
export {
  features,
  featureScenarios,
  runs,
  nodeAttempts,
  contracts,
  commits,
  fixTasks,
  reflections,
  runEvents,
  projects,
  type FeatureRow,
  type FeatureInsert,
  type FeatureScenarioRow,
  type FeatureScenarioInsert,
  type RunRow,
  type RunInsert,
  type NodeAttemptRow,
  type NodeAttemptInsert,
  type ContractRow,
  type ContractInsert,
  type CommitRow,
  type CommitInsert,
  type FixTaskRow,
  type FixTaskInsert,
  type ReflectionRow,
  type ReflectionInsert,
  type RunEventRow,
  type RunEventInsert,
  type ProjectRow,
  type ProjectInsert,
} from "./schema";
export {
  newRunId,
  cellId,
  getFeatureRow,
  upsertFeature,
  updateFeatureScenarios,
  createFeatureManual,
  updateFeatureMeta,
  archiveFeature,
  listActiveFeatures,
  createScenarioManual,
  deleteScenario,
  getCellRow,
  upsertFeatureScenario,
  getFeatureScenario,
  listFeatureScenarios,
  updateCellAgentStatus,
  updateFeatureScenarioStatus,
  hasRunningRun,
  createRun,
  updateRun,
  ensureVirtualCell,
  createAttempt,
  updateAttempt,
  createContract,
  getContractById,
  getLatestContract,
  updateContractStatus,
  createCommit,
  getLatestCommit,
  getLatestRunByKind,
  listRunsByKind,
  getRunById,
  createFixTask,
  listFixTasks,
  createReflection,
  listReflectionsForFeature,
  createRunEvent,
  listRunEvents,
  listAttemptsForRuns,
  type UpsertFeatureArgs,
  type UpsertFeatureScenarioArgs,
  type CreateFeatureManualArgs,
  type UpdateFeatureMetaArgs,
  type CreateScenarioManualArgs,
  type RunKind,
  type RunState,
  type AttemptStatus,
  type UpdateAttemptArgs,
  type ContractStatus,
  type CreateContractArgs,
  type CreateCommitArgs,
  type CreateFixTaskArgs,
  type CreateReflectionArgs,
  createProject,
  getProjectById,
  listProjectsDb,
  updateProject,
  softDeleteProject,
  reactivateProject,
  type CreateProjectArgs,
  type UpdateProjectArgs,
  countFeaturesByProject,
  countFeaturesByStatus,
  cleanupStaleRuns,
  listRunsForCell,
  listContractsForCell,
  listCommitsForCell,
} from "./repo";
