export { createDb, type DB } from "./db";
export {
  features,
  featureScenarios,
  runs,
  nodeAttempts,
  contracts,
  commits,
  fixTasks,
  reflections,
  runEvents,
  projects,
  requirements,
  contractSyncResults,
  contractCellMappings,
  standardsMigrations,
  pipelineQueue,
  llmProviders,
  runtimeSettings,
  type FeatureRow,
  type FeatureInsert,
  type FeatureScenarioRow,
  type FeatureScenarioInsert,
  type RunRow,
  type RunInsert,
  type NodeAttemptRow,
  type NodeAttemptInsert,
  type ContractRow,
  type ContractInsert,
  type CommitRow,
  type CommitInsert,
  type FixTaskRow,
  type FixTaskInsert,
  type ReflectionRow,
  type ReflectionInsert,
  type RunEventRow,
  type RunEventInsert,
  type ProjectRow,
  type ProjectInsert,
  type RequirementRow,
  type RequirementInsert,
  type ContractSyncResultRow,
  type ContractSyncResultInsert,
  type ContractCellMappingRow,
  type ContractCellMappingInsert,
  type StandardsMigrationRow,
  type StandardsMigrationInsert,
  type PipelineQueueRow,
  type PipelineQueueInsert,
  type LLMProviderRow,
  type RuntimeSettingsRow,
  pendingMerges,
  type PendingMergeRow,
  type PendingMergeInsert,
} from "./schema";
export {
  newRunId,
  cellId,
  getFeatureRow,
  upsertFeature,
  updateFeatureScenarios,
  createFeatureManual,
  updateFeatureMeta,
  updateFeatureImplementation,
  archiveFeature,
  archiveFeatureScenario,
  listActiveFeatures,
  generateFeatureId,
  createScenarioManual,
  deleteScenario,
  getCellRow,
  upsertFeatureScenario,
  getFeatureScenario,
  listFeatureScenarios,
  updateCellAgentStatus,
  updateFeatureScenarioStatus,
  hasRunningRun,
  createRun,
  updateRun,
  ensureVirtualCell,
  VIRTUAL_CELL_ID,
  type WorkUnit,
  cellOf,
  requirementIdOf,
  createAttempt,
  updateAttempt,
  createContract,
  getContractById,
  getLatestContract,
  updateContractStatus,
  createCommit,
  getLatestCommit,
  getLatestRunByKind,
  listRunsByKind,
  listRunningRuns,
  listRecentRuns,
  getRunsLastActivity,
  getRunById,
  createFixTask,
  listFixTasks,
  createReflection,
  listReflectionsForFeature,
  createRunEvent,
  listRunEvents,
  listStructuralRunEvents,
  getLatestRequireInput,
  type RequireInputSummary,
  listAttemptsForRuns,
  type UpsertFeatureArgs,
  type UpsertFeatureScenarioArgs,
  type CreateFeatureManualArgs,
  type UpdateFeatureMetaArgs,
  type CreateScenarioManualArgs,
  type RunKind,
  type RunState,
  type AttemptStatus,
  type UpdateAttemptArgs,
  type ContractStatus,
  type CreateContractArgs,
  type CreateCommitArgs,
  type CreateFixTaskArgs,
  type CreateReflectionArgs,
  createProject,
  getProjectById,
  listProjectsDb,
  updateProject,
  softDeleteProject,
  reactivateProject,
  updateProjectStandards,
  type CreateProjectArgs,
  type UpdateProjectArgs,
  countFeaturesByProject,
  countFeaturesByStatus,
  cleanupStaleRuns,
  listRunsForCell,
  listContractsForCell,
  listCommitsForCell,
  listContractsForFeature,
  listRunsForFeature,
  upsertContractSyncResult,
  listSyncResultsByProject,
  listSyncResultsByState,
  getSyncResult,
  markSyncResultMatched,
  upsertContractCellMapping,
  listContractCellMappings,
  getContractCellMapping,
  createMigration,
  listMigrations,
  getLatestMigration,
  type ContractSyncState,
  type UpsertContractSyncResultArgs,
  type UpsertContractCellMappingArgs,
  type MigrationAction,
  type CreateMigrationArgs,
  // pipeline_queue — 常驻 worker 执行队列
  type PipelineQueueState,
  type EnqueueArgs,
  enqueueIfAbsent,
  claimNextPending,
  markQueueDone,
  markQueueTerminal,
  listRunningQueue,
  requeueAfterCrash,
  listQueue,
  countQueueByState,
  sumNodeDoneCostSince,
  listApprovedContracts,
  clearTerminalQueueForCell,
  clearAllQueueForCell,
  // llm_providers — 大模型 provider 配置(API Key 管理)
  createLLMProvider,
  getLLMProviderById,
  listLLMProviders,
  updateLLMProvider,
  setActiveLLMProvider,
  getActiveLLMProvider,
  deleteLLMProvider,
  type CreateLLMProviderArgs,
  type UpdateLLMProviderArgs,
  // runtime_settings — 平台运行参数(前端可配,start 路由注入 env)
  getRuntimeSettings,
  updateRuntimeSettings,
  DEFAULT_RUNTIME_SETTINGS,
  type UpdateRuntimeSettingsArgs,
  // WorkUnit + 需求驱动通路(requirements)
  type RequirementStatus,
  type RequirementAgentStatus,
  type CreateRequirementArgs,
  createRequirement,
  getRequirement,
  listRequirementsByProject,
  updateRequirementStatus,
  updateRequirementAgentStatus,
  setRequirementSession,
  setRequirementClarifyRun,
  getLatestContractWorkUnit,
  getLatestCommitWorkUnit,
  getLatestRunByKindWorkUnit,
  listFixTasksWorkUnit,
  listReflectionsForWorkUnit,
  // pending_merges — 待人工确认合并的 worktree 快照
  createPendingMerge,
  getPendingMerge,
  deletePendingMerge,
  type CreatePendingMergeArgs,
} from "./repo";
